name: Docker Build

on:
  push:
    branches:
      - main  # 触发工作流的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t lbp2900_network_printer_docker:latest .
