name: Docker Build

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Build Docker image
        run: docker build -t lbp2900_printer:latest .
