name: Docker Build and Save Artifact

on:
  push:
    branches:
      - main  # 触发工作流的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t lbp2900-cups .

      # 4. 将镜像保存为 tar 文件
      - name: Save Docker image as artifact
        run: docker save -o lbp2900-cups.tar lbp2900-cups

      # 5. 上传 tar 文件为构建产物
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lbp2900-cups-image
          path: lbp2900-cups.tar
